const SET_DATA = "SET_DATA";
const SET_NEXT_PAGE_TOKEN = "SET_NEXT_PAGE_TOKEN";
const SET_SEARCH = "SET_SEARCH";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_PAGE = "SET_PAGE";
const SET_TOTAL_COUNT = "TOTAL_COUNT";
const SET_ID = "SET_ID";
const SET_LIKES = "SET_LIKES";

export {
  SET_DATA,
  SET_NEXT_PAGE_TOKEN,
  SET_SEARCH,
  SET_CURRENT_PAGE,
  SET_PAGE,
  SET_TOTAL_COUNT,
  SET_ID,
  SET_LIKES,
};
