const SET_DATA = "SET_DATA";
const SET_NEXT_PAGE_TOKEN = "SET_NEXT_PAGE_TOKEN";
const SET_SEARCH = "SET_SEARCH";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_PAGE = "SET_PAGE";

// export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
// export const PAGE_TOKENS = "PAGE_TOKENS";
// export const PAGE_SCROLL = "PAGE_SCROLL";
// export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
// export const TOTAL_COUNT = "TOTAL_COUNT";

export { SET_DATA, SET_NEXT_PAGE_TOKEN, SET_SEARCH, SET_CURRENT_PAGE, SET_PAGE };
